steps:
  # Debugging step: Check environment variables and substitutions before build
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Debug Before Build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Environment Variables and Substitutions Before Build:"
        env
        echo "Substitutions:"
        echo "PROJECT_ID: ${_PROJECT_ID}"
        echo "PROJECT_NUMBER: ${_PROJECT_NUMBER}"
        echo "LOG_BUCKET: ${_LOG_BUCKET}"
        echo "INSTANCE_CONNECTION_NAME: ${_INSTANCE_CONNECTION_NAME}"

  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_APP_NAME}:$SHORT_SHA', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    args: ['push', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_APP_NAME}:$SHORT_SHA']



  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to Cloud Run..."
        gcloud run deploy my-flask123 \
          --image=us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_APP_NAME}:$SHORT_SHA \
          --region=us-central1 \
          --platform=managed \
          --allow-unauthenticated \
          --service-account="$_SA_CLOUD_RUN" \
          --add-cloudsql-instances=spn-run:us-central1:spn-sql \
          --set-env-vars DB_USER="$_DB_USER" \
          --set-env-vars DB_PASSWORD="$_DB_PASSWORD" \
          --set-env-vars INSTANCE_CONNECTION_NAME="${_INSTANCE_CONNECTION_NAME}"
  

images:
  - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_APP_NAME}:$SHORT_SHA'

timeout: '1200s'

substitutions:
  _APP_NAME: "my-flask1"
  _ARTIFACT_REPO: "spn-art"
  _INSTANCE_CONNECTION_NAME: "spn-run:us-central1:spn-sql"
  _DB_USER: "db-user"
  _DB_PASSWORD: "db-password"
  _SA_CLOUD_RUN: "sa-cloud-run@spn-run.iam.gserviceaccount.com"

options:
  env:
    - PROJECT_ID=${_PROJECT_ID}
    - PROJECT_NUMBER=${_PROJECT_NUMBER}
    - LOG_BUCKET=${_LOG_BUCKET}

logsBucket: "gs://${_LOG_BUCKET}"