steps:
  # Debugging step: Check environment variables and substitutions before build
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Debug Before Build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Environment Variables and Substitutions Before Build:"
        env
        echo "Substitutions:"
        echo "PROJECT_ID: ${_PROJECT_ID}"
        echo "PROJECT_NUMBER: ${_PROJECT_NUMBER}"
        echo "LOG_BUCKET: ${_LOG_BUCKET}"
        echo "INSTANCE_CONNECTION_NAME: ${_INSTANCE_CONNECTION_NAME}"

  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_APP_NAME}:$SHORT_SHA', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    args: ['push', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_APP_NAME}:$SHORT_SHA']

  # Step 3: Fetch secrets
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Fetch Secrets'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching Secrets..."
        export DB_USER=$(gcloud secrets versions access latest --secret=db-user)
        export DB_PASSWORD=$(gcloud secrets versions access latest --secret=db-password)
        echo "Secrets fetched."

  # Debugging step: Before deployment to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Debug Before Deployment'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Environment Variables Before Deployment:"
        echo "DB_USER: $DB_USER"
        echo "DB_PASSWORD: $DB_PASSWORD"
        echo "INSTANCE_CONNECTION_NAME: ${_INSTANCE_CONNECTION_NAME}"

  # Debugging step: Check environment variables and substitutions after build
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Debug After Build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Environment Variables and Substitutions After Build:"
        env
        echo "Substitutions:"
        echo "PROJECT_ID: ${_PROJECT_ID}"
        echo "PROJECT_NUMBER: ${_PROJECT_NUMBER}"
        echo "LOG_BUCKET: ${_LOG_BUCKET}"
        echo "INSTANCE_CONNECTION_NAME: ${_INSTANCE_CONNECTION_NAME}"
        
images:
  - 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REPO}/${_APP_NAME}:$SHORT_SHA'

timeout: '1200s'

substitutions:
  _APP_NAME: "my-flask1"
  _ARTIFACT_REPO: "spn-art"
  _INSTANCE_CONNECTION_NAME: "spn-run:us-central1:spn-sql"

options:
  env:
    - PROJECT_ID=${_PROJECT_ID}
    - PROJECT_NUMBER=${_PROJECT_NUMBER}
    - LOG_BUCKET=${_LOG_BUCKET}

logsBucket: "gs://${_LOG_BUCKET}"