steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Test Secret Access'
    secretEnv: ['DB_USER']
    args:
      - 'echo'
      - '$DB_USER'

secrets:
  - secretEnv:
      DB_USER: projects/spn-run/secrets/db-user/versions/latest


options:
  env:
    - PROJECT_ID=${_PROJECT_ID}
    - PROJECT_NUMBER=${_PROJECT_NUMBER}
    - LOG_BUCKET=${_LOG_BUCKET}

logsBucket: "gs://${_LOG_BUCKET}"

